export const DOGBREEDS_FETCHING_SUCCESS = "DOGBREEDS_FETCHING_SUCCESS";
export const DOGBREEDS_FETCHING_FAILURE = "DOGBREEDS_FETCHING_FAILURE";

export const DOGIMAGES_FETCHING_SUCCESS = "DOGIMAGES_FETCHING_SUCCESS";
export const DOGIMAGES_FETCHING_FAILURE = "DOGIMAGES_FETCHING_FAILURE";
